version: "3.8"

services:
  grobid:
    image: lfoppiano/grobid:0.8.1
    container_name: grobid
    ports:
      - "8070:8070"
    networks:
      - service_net
    volumes:
      - ./grobid_data/input:/opt/grobid/input
      - ./grobid_data/output:/opt/grobid/output
      - ./grobid_data/config:/opt/grobid/config
      - ./process.sh:/opt/grobid/process.sh

networks:
  service_net:
    driver: bridge